quarkus:
  datasource:
    username: hebzkbet
    password: hNIb6nhqrRSiNhyYXbZVlkQbUFNL5jKY
    jdbc:
      url: jdbc:postgresql://arjuna.db.elephantsql.com:5432/hebzkbet
    db-kind: postgresql
  http:
    port: 8081


#quarkus.datasource.db-kind=postgresql
#quarkus.datasource.username=postgres
#quarkus.datasource.password=postgres
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
#quarkus.datasource.jdbc.max-size=16
#quarkus.http.port=8081